name: Run Python Script Every Minute

on:
  schedule:
    - cron: "*/1 * * * *"  # This will run every minute
  workflow_dispatch:  # This allows you to manually trigger the workflow as well

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v3

    - name: Set up Python (system version)
      uses: actions/setup-python@v4
      with:
        python-version: 'system'  # Let the GitHub runner use the system Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install prefect psycopg2

    - name: Run Python script
      run: |
        python pipeline.py  # Use 'python' (system Python version) here
