
name: Run Python Script Every Minute

on:
  schedule:
    - cron: "*/1 * * * *"  
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from GitHub
      uses: actions/checkout@v3

    - name: Set up Python (use pre-installed version)
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-dev
        python3 -m pip install --upgrade pip
        pip3 install prefect psycopg2  
        

    - name: Run Python script
      run: |
        python3 pipeline.py  # Use system Python 3
